name: Generate Release

on:
  # pull_request:
  #   types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  Publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: ''
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true

      - name: Create release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.versioning.outputs.version }}
          name: ${{ steps.versioning.outputs.version }}
          generate_release_notes: true
          prerelease: false
