name: Generate Release

on: 
  pull_request:
    types: [opened, reopened]

  # push:
  #   branches:
  #     - main

jobs:
  Publish-release:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: test
        run: | 
          ls -lha
        shell: bash
