name: Generate Release

on:
  # pull_request:
  #   types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  Publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch all commits
          fetch-depth: 0

      # - name: test
      #   run: |
      #     ls -lha
      #   shell: bash

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
         # branch: main
          tag_prefix: ''
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          format: "${major}.${minor}.${patch}"

      - name: Create release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ steps.versioning.outputs.version }}
          automatic_release_tag: ${{ steps.versioning.outputs.version }}
          prerelease: false
